#!/bin/sh

TITLE=$1

#DATE_FORMAT="%Y.%m.%dT%H.%M.%S"
DATE_FORMAT="%Y.%m.%d"
DT_STAMP=$(date +"${DATE_FORMAT}")

if [ $# -lt 1 ]; then
  HASH=$(echo $RANDOM | md5 | head -c 7)
else
  HASH=${TITLE}
fi

FILENAME=${DT_STAMP}.${HASH}.md
echo ${FILENAME}
touch ${FILENAME}